### PR TITLE
Chapter 2 Examples.

### PR DESCRIPTION
**Pull request by abhikpal**
Ported chapter 2 examples from [The-Nature-of-Code-Examples](https://github.com/shiffman/The-Nature-of-Code-Examples) to Python. The file naming convention and the directory structure of the original repo has been maintained.

### CODE REVIEW

**Comment by shiffman** [comment]
Amazing, thank you!

**Comment by jdf** [comment]
Seconded; thanks very much.

**Comment by abhikpal** [comment]
I've set myself on the ambitious task of porting the full book if I end up taking a gap year. I'm working my way through the third chapter now. More pull requests should be here soon.

**Comment by jdf** [comment]
this is amazing

**Pull request merged**
